CREATE TABLE CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCTS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    UNIT_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INTEGER REFERENCES CUSTOMERS (ID),
    ORDER_DATE TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ORDER_ITEMS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES ORDERS (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCTS (ID),
    AMOUNT INTEGER
);